name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.10
  - anaconda=custom
  - anaconda-client=1.6.14
  - anaconda-navigator=1.9.7
  - anaconda-project=0.8.2
  - asn1crypto=0.24.0
  - astroid=1.6.3
  - astropy=3.0.2
  - atomicwrites=1.3.0
  - attrs=18.1.0
  - babel=2.5.3
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.6.0
  - bitarray=0.8.1
  - bkcharts=0.2
  - blas=1.0
  - blaze=0.11.3
  - bleach=2.1.3
  - blosc=1.14.3
  - bokeh=0.12.16
  - boto=2.48.0
  - bottleneck=1.2.1
  - bqplot=0.12.6
  - branca=0.3.1
  - bzip2=1.0.6
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - certifi=2019.11.28
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - cloudpickle=0.5.3
  - clyent=1.2.2
  - colorama=0.3.9
  - comtypes=1.1.4
  - conda=4.8.3
  - conda-build=3.10.5
  - conda-env=2.6.0
  - conda-package-handling=1.6.0
  - conda-verify=2.0.0
  - console_shortcut=0.1.1
  - contextlib2=0.5.5
  - cryptography=2.8
  - curl=7.68.0
  - cycler=0.10.0
  - cython=0.28.2
  - cytoolz=0.9.0.1
  - dask=0.17.5
  - dask-core=0.17.5
  - datashape=0.5.4
  - decorator=4.3.0
  - defusedxml=0.6.0
  - distributed=1.21.8
  - docutils=0.14
  - earthengine-api=0.1.217
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - fastcache=1.0.2
  - filelock=3.0.4
  - flask=1.0.2
  - flask-cors=3.0.4
  - folium=0.10.1
  - freetype=2.8
  - future=0.18.2
  - geemap=0.4.0
  - get_terminal_size=1.0.0
  - gevent=1.3.0
  - glob2=0.6
  - google-api-core=1.16.0
  - google-api-python-client=1.8.0
  - google-auth=1.7.1
  - google-auth-httplib2=0.0.3
  - google-cloud-core=1.3.0
  - google-cloud-storage=1.23.0
  - google-resumable-media=0.5.0
  - googleapis-common-protos=1.51.0
  - greenlet=0.4.13
  - h5py=2.7.1
  - hdf5=1.10.2
  - heapdict=1.0.0
  - html5lib=1.0.1
  - httplib2=0.17.0
  - icc_rt=2017.0.4
  - icu=58.2
  - idna=2.6
  - imageio=2.3.0
  - imagesize=1.0.0
  - importlib_metadata=1.5.0
  - intel-openmp=2018.0.0
  - ipykernel=4.8.2
  - ipyleaflet=0.12.3
  - ipynb-py-convert=0.4.5
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.4
  - itsdangerous=0.24
  - jdcal=1.4
  - jedi=0.12.0
  - jinja2=2.10
  - jpeg=9b
  - json5=0.9.3
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - jupyterlab=0.32.1
  - jupyterlab_launcher=0.10.5
  - jupyterlab_server=1.0.0
  - keyring=21.1.0
  - kiwisolver=1.0.1
  - krb5=1.17.1
  - lazy-object-proxy=1.3.1
  - libcurl=7.68.0
  - libiconv=1.15
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libsodium=1.0.16
  - libssh2=1.9.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.23.1
  - locket=0.2.0
  - lxml=4.2.1
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mccabe=0.6.1
  - menuinst=1.4.14
  - mistune=0.8.3
  - mkl=2018.0.2
  - mkl-service=1.1.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - more-itertools=4.1.0
  - mpmath=1.0.0
  - msgpack-python=0.5.6
  - msys2-conda-epoch=20160418
  - multipledispatch=0.5.0
  - navigator-updater=0.2.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - networkx=2.1
  - nltk=3.3.0
  - nose=1.3.7
  - notebook=5.5.0
  - numba=0.38.0
  - numexpr=2.6.5
  - numpy=1.14.3
  - numpy-base=1.14.3
  - numpydoc=0.8.0
  - odo=0.5.1
  - olefile=0.45.1
  - openpyxl=2.5.3
  - openssl=1.1.1e
  - packaging=17.1
  - pandas=0.23.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.2.0
  - partd=0.3.8
  - path.py=11.0.1
  - pathlib2=2.3.2
  - patsy=0.5.0
  - pep8=1.7.1
  - pickleshare=0.7.4
  - pillow=5.1.0
  - pip=10.0.1
  - pkginfo=1.4.2
  - pluggy=0.6.0
  - ply=3.11
  - powershell_shortcut=0.0.1
  - prometheus_client=0.7.1
  - prompt_toolkit=1.0.15
  - protobuf=3.11.4
  - psutil=5.4.5
  - py=1.5.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.4.0
  - pycosat=0.6.3
  - pycparser=2.18
  - pycrypto=2.6.1
  - pycurl=7.43.0.5
  - pyflakes=1.6.0
  - pygments=2.2.0
  - pylint=1.8.4
  - pyodbc=4.0.23
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.15.7
  - pysocks=1.6.8
  - pytables=3.4.3
  - pytest=3.5.1
  - pytest-arraydiff=0.2
  - pytest-astropy=0.3.0
  - pytest-doctestplus=0.1.3
  - pytest-openfiles=0.3.0
  - pytest-remotedata=0.2.1
  - python=3.6.5
  - python-dateutil=2.7.3
  - python_abi=3.6
  - pytz=2018.4
  - pywavelets=0.5.2
  - pywin32=223
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.1
  - pyyaml=3.12
  - pyzmq=17.0.0
  - qt=5.9.7
  - qtawesome=0.4.4
  - qtconsole=4.3.1
  - qtpy=1.4.1
  - requests=2.18.4
  - rope=0.10.7
  - rsa=4.0
  - ruamel_yaml=0.15.35
  - scikit-image=0.13.1
  - scipy=1.1.0
  - seaborn=0.8.1
  - selenium=3.141.0
  - send2trash=1.5.0
  - setuptools=39.1.0
  - simplegeneric=0.8.1
  - simplejson=3.17.0
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.11.0
  - snappy=1.1.7
  - snowballstemmer=1.2.1
  - sortedcollections=0.6.1
  - sortedcontainers=1.5.10
  - soupsieve=2.0
  - sphinx=1.7.4
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - spyder=3.2.8
  - spyder-kernels=1.4.0
  - sqlalchemy=1.2.7
  - sqlite=3.31.1
  - statsmodels=0.9.0
  - sympy=1.1.1
  - tbb=2020.0
  - tbb4py=2020.0
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.0.2
  - tqdm=4.42.1
  - traitlets=4.3.2
  - traittypes=0.2.1
  - typed-ast=1.4.1
  - typing=3.6.4
  - unicodecsv=0.14.1
  - uritemplate=3.0.1
  - urllib3=1.22
  - vc=14.1
  - vincent=0.4.4
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.31.1
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.0.1
  - win_unicode_console=0.5
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.10.11
  - xarray=0.13.0
  - xlrd=1.1.0
  - xlsxwriter=1.0.4
  - xlwings=0.11.8
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cdsapi==0.3.0
    - joblib==0.14.1
    - scikit-learn==0.22.2.post1
prefix: C:\Users\wangj\Anaconda3

